// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0j3DRSxsaJdstdFnY0BX_Kks5PInYTZk',
    appId: '1:1066277289933:web:360d85511d591d8710ce84',
    messagingSenderId: '1066277289933',
    projectId: 'cybehawks-news',
    authDomain: 'cybehawks-news.firebaseapp.com',
    storageBucket: 'cybehawks-news.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-buif9RVHUfoz8W3AkI260oibtlQRjbg',
    appId: '1:1066277289933:android:8aed6d87e7c086ab10ce84',
    messagingSenderId: '1066277289933',
    projectId: 'cybehawks-news',
    storageBucket: 'cybehawks-news.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB7YcjDHmFVwwlQRXVU8qPkfZvmH8p4cw',
    appId: '1:1066277289933:ios:44cf5ad1f882c14f10ce84',
    messagingSenderId: '1066277289933',
    projectId: 'cybehawks-news',
    storageBucket: 'cybehawks-news.appspot.com',
    androidClientId: '1066277289933-48ringaaob04h33q3uq7olkbmf7begm9.apps.googleusercontent.com',
    iosClientId: '1066277289933-cj09vf1j3ie1fa51v3ktk1e354lipmlp.apps.googleusercontent.com',
    iosBundleId: 'com.cyberhawks',
  );
}
